site_name: Hyperlinked Twins
site_url: https://pdmosses.github.io/hyperlinked-twins/
repo_name: pdmosses/hyperlinked-twins
repo_url: https://github.com/pdmosses/hyperlinked-twins

theme:
  name: material

  features:
    - content.code.copy
    # - navigation.expand
    - navigation.indexes 
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: false
      strict: false
      order: asc
      sort_type: natural
      order_by: title

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences
